{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_alluredemo.TestLogin object at 0x03EFA110>\n\n    @allure.story(\"密码错误\")\n    def test_login_failure(self):\n        # with allure.step放在测试用例中，测试步骤\n        # @allure.step 测试步骤\n        with allure.step(\"输入用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_alluredemo.py:23: AssertionError"}, "steps": [{"name": "输入用户名", "status": "passed", "start": 1662627341572, "stop": 1662627341572}, {"name": "输入密码", "status": "passed", "start": 1662627341572, "stop": 1662627341572}, {"name": "登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\git\\Learn\\pytest\\2022_09_06\\test_alluredemo.py\", line 23, in test_login_failure\n    assert '1' == 1\n"}, "start": 1662627341572, "stop": 1662627341573}], "start": 1662627341572, "stop": 1662627341573, "uuid": "41348245-1c79-446f-903e-c172147fc683", "historyId": "6ce617641cf7fa3edb9f52b1944a5859", "testCaseId": "3c5a8d65ef7e767f5436c3d42af48b32", "fullName": "test_alluredemo.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "密码错误"}, {"name": "suite", "value": "test_alluredemo"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IJJSVRT"}, {"name": "thread", "value": "17084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}