{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n        # assert 断言判断func(3)是否满足期望值\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_demo1.py:13: AssertionError"}, "start": 1662626492610, "stop": 1662626492610, "uuid": "7879b7fe-6f1c-49c4-a2d2-137c9687619e", "historyId": "6b1f5943849efe54591b56208eb6cba4", "testCaseId": "78b5b94153aba2bc12f69794ff671308", "fullName": "test_demo1#test_answer", "labels": [{"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-IJJSVRT"}, {"name": "thread", "value": "3240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo1"}]}